#!/Python27/python
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')   
print ('<title>Hello Word - Python CGI Program</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hello Word! This is my Python CGI program</h2>')
print ('</body>')
print ('</html>')