top_srcdir   = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
top_builddir = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
srcdir       = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/metadata
builddir     = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/metadata
VPATH        = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/metadata

include $(top_srcdir)/build/special.mk

