top_srcdir   = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
top_builddir = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
srcdir       = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/arch/unix
builddir     = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/arch/unix
VPATH        = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/modules/arch/unix

include $(top_srcdir)/build/special.mk

