top_srcdir   = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
top_builddir = /home/pi/Desktop/apache2.4.25/httpd-2.4.25
srcdir       = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/server/mpm
builddir     = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/server/mpm
VPATH        = /home/pi/Desktop/apache2.4.25/httpd-2.4.25/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
